#!/bin/bash

echo "🚀 Setting up AI Development Environment..."
echo "=========================================="

# Install dependencies
echo "📦 Installing Python dependencies..."
python3 -m pip install --user aider-chat flask flask-cors
export PATH="$PATH:/home/codespace/.local/bin"

# Create Aider config
echo "⚙️ Creating Aider configuration..."
cat > .aider.conf.yml << 'EOF'
# Using DeepInfra Qwen 2.5 Coder 32B
model: deepinfra/Qwen/Qwen2.5-Coder-32B-Instruct
api-base: https://api.deepinfra.com/v1/openai
auto-commits: true
pretty: true
stream: true
show-diffs: true
git-user-name: "AI Developer"
git-user-email: "ai@codespace.dev"
EOF

# Setup environment
echo "🔧 Setting up environment..."
cat > .env.local << 'EOF'
# DeepInfra API Key for Qwen 2.5 Coder 32B
DEEPINFRA_API_KEY=your_deepinfra_api_key_here

# For compatibility with Aider (it looks for OPENAI_API_KEY)
OPENAI_API_KEY=${DEEPINFRA_API_KEY}

# Database URL (will be configured by Aider)
DATABASE_URL="postgresql://username:password@localhost:5432/database"

# NextAuth Configuration
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=your-secret-here
EOF

# Create initial git commit
git add .
git commit -m "Initial project setup with AI instructions"

echo ""
echo "✅ Setup Complete!"
echo "=================="
echo ""
echo "🤖 **Start AI Development:**"
echo "   aider"
echo ""
echo "📋 **Development Guide:**"
echo "   1. Aider will read AIDER_INSTRUCTIONS.md automatically"
echo "   2. Follow the step-by-step implementation plan"
echo "   3. All code will be generated by AI"
echo ""
echo "🔑 **Important**: Add your DeepInfra API key to .env.local"
echo "   Get your key at: https://deepinfra.com/dash/api_keys"
echo ""
echo "🚀 Ready for AI-powered development!"
