name: Setup Repository Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/setup-secrets.yml'

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Check for DEEPINFRA_API_KEY
        id: check_key
        run: |
          if [ -n "${{ secrets.DEEPINFRA_API_KEY }}" ]; then
            echo "::set-output name=has_key::true"
            echo "✅ DEEPINFRA_API_KEY is already set"
          else
            echo "::set-output name=has_key::false"
            echo "⚠️ DEEPINFRA_API_KEY is not set"
            echo ""
            echo "To enable AI auto-development, please set the DEEPINFRA_API_KEY secret:"
            echo "1. Go to Settings → Secrets and variables → Actions"
            echo "2. Click 'New repository secret'"
            echo "3. Name: DEEPINFRA_API_KEY"
            echo "4. Value: Your DeepInfra API key for Qwen 2.5 Coder 32B"
            echo "5. Get your API key at: https://deepinfra.com/dash/api_keys"
          fi
      
      - name: Setup notification
        if: steps.check_key.outputs.has_key != 'true'
        run: |
          echo "::warning::DeepInfra API key is not configured. AI auto-development features will not work until you add the DEEPINFRA_API_KEY secret."
